### ISSUE TITLE
IntelliJ/GradleRIO

### ISSUE THREAD

**Issue by H1ppx** [MontclairRobotics/PowerUp#9]
currently builds with 72 errors all which result from sprocket "not existing". I made a test mode and it builds fine without sprocket.

**Comment by H1ppx** [comment]
Update: build successful, testing later today

**Comment by H1ppx** [comment]
Yay it works for the one computer, time to make it work for all computers

**Comment by rafibaum** [comment]
Merge from master as a PR was just merged to get Travis working. That way each time you'll commit, you'll have Travis check your Gradle config.

**Comment by rafibaum** [comment]
See #12 . Implemented a Gradle base which needs testing.

**Comment by GarrettBurroughs** [comment]
Is working now
